### ISSUE TITLE
MSGR-0011 Notifications

### ISSUE THREAD

**Issue by lopei** [lopei/MessengerNew#18]
В full версии на странице настроек пропадает пункт "УВедомления"

**Comment by metalurgus** [comment]
Уведомления убираются в Android O:
https://github.com/lopei/MessengerNew/blob/c5c472b16589d5ca6733c01ef7c874b81eab1614/app/src/main/java/com/anotap/messenger/fragment/PreferencesFragment.java#L241

**Comment by lopei** [comment]
Пусть будут и в О

**Comment by metalurgus** [comment]
там другая фигня, они как-то распределяются на каналы в О, а до О надо руками это делать

**Comment by lopei** [comment]
Тогда пусть будет так уже
