### ISSUE TITLE
MSGR-0013 Proxy Connection 

### ISSUE THREAD

**Issue by lopei** [lopei/MessengerNew#20]
Периодически появляется надпиcь "Failed to connect to... [ip]", данную ошибку отображать не нужнр

**Comment by metalurgus** [comment]
не могу воспроизвести, и не имею понятия, где искать

**Comment by lopei** [comment]
Выключи интернет и попробуй загрузить любую страницу

**Comment by metalurgus** [comment]
Done in #25
