### ISSUE TITLE
MSGR 0015 - Backgrounds

### ISSUE THREAD

**Issue by lopei** [lopei/MessengerNew#24]
Поменять бекграунд в хэдере меню на :

<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <gradient
        android:angle="270"
        android:endColor="@color/colorPrimaryDark"
        android:startColor="@color/colorPrimary" />
</shape>

**Comment by metalurgus** [comment]
Done in #26
